site_name: Awakatime
site_author: Controlado
site_description: Asynchronous API wrapper for Wakatime
repo_name: controlado/awakatime
repo_url: https://github.com/controlado/awakatime
edit_uri: edit/master/docs/

theme:
  name: material
  language: en
  features:
    - header.autohide
    - navigation.tabs
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      primary: white
      accent: blue

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths:
            - awakatime

markdown_extensions:
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.highlight
