name: Coverage

on:
  workflow_dispatch:
  push:
    paths:
      - awakatime/**
      - tests/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Instalando o Poetry
        uses: abatilo/actions-poetry@v2

      - name: Instalando dependências
        run: poetry install --with dev

      - name: Rodando os testes
        run: poetry run pytest --cov --cov-report=xml
        env:
            WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}

      - name: Subindo o coverage para o Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          flags: unittests
          token: ${{ secrets.CODECOV_TOKEN }}
